version: "3.7" 
 services: 
   website: 
     container_name: website 
     restart: always 
     build: 
       context: ./website 
       dockerfile: Dockerfile 
     environment: 
       - FLASK_ENV=dev 
       - FLASK_APP=./website/app/main.py 
       - FLASK_RUN_HOST=0.0.0.0 
     ports: 
       - 8000:8000 
     volumes: 
       - .:/website
  